# Generated by Django 4.2.29 on 2026-03-11 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Pet Owner'), ('vet', 'Veterinarian'), ('shelter', 'Animal Shelter'), ('store', 'Pet Store Owner'), ('provider', 'Service Provider')], default='owner', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('grooming', 'Pet Grooming'), ('walking', 'Dog Walking'), ('sitting', 'Pet Sitting'), ('training', 'Pet Training'), ('boarding', 'Pet Boarding'), ('transport', 'Pet Transport'), ('photography', 'Pet Photography')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('price_range', models.CharField(blank=True, help_text='e.g. ₹500 - ₹2000', max_length=100)),
                ('working_hours', models.CharField(default='9 AM - 6 PM', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='myapp.pet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.serviceprovider')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
