# Generated by Django 4.2.29 on 2026-03-13 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customerorder_supplier_productinventory_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('shampoo', 'Shampoo'), ('conditioner', 'Conditioner'), ('blades', 'Grooming Blades'), ('ear_cleaning', 'Ear Cleaning Solution'), ('de_shedding', 'De-shedding Spray'), ('other', 'Other')], default='other', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='bottle', max_length=30)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_supplies', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_supplies', to='myapp.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(choices=[('bath_brush', 'Bath & Brush'), ('full_groom', 'Full Groom'), ('breed_cut', 'Breed Cut'), ('nail_trim', 'Nail Trim'), ('de_shedding', 'De-shedding')], default='full_groom', max_length=30),
        ),
        migrations.CreateModel(
            name='GroomingSupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='ordered', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_supply_orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_supply_orders', to='myapp.serviceprovider')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.groomingsupply')),
            ],
        ),
        migrations.CreateModel(
            name='GroomingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('bath_brush', 'Bath & Brush'), ('full_groom', 'Full Groom'), ('breed_cut', 'Breed Cut'), ('nail_trim', 'Nail Trim'), ('de_shedding', 'De-shedding')], default='full_groom', max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('special_notes', models.TextField(blank=True)),
                ('session_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_session', to='myapp.servicebooking')),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_sessions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_grooming_sessions', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_sessions', to='myapp.pet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_sessions', to='myapp.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCareNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.TimeField()),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_notes', to='myapp.servicebooking')),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_care_notes', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_notes', to='myapp.pet')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_care_notes', to='myapp.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
