# Generated by Django 4.2.29 on 2026-03-13 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_groomingsupply_servicebooking_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('notification_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_appointments', to='myapp.vetclinic')),
                ('linked_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_request', to='myapp.appointment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_appointments', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_appointments', to='myapp.pet')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_vaccination_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('administered_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('due_soon', 'Due Soon'), ('scheduled', 'Scheduled')], default='scheduled', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='myapp.vaccinationappointment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='myapp.pet')),
                ('vet_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='myapp.vetclinic')),
            ],
            options={
                'ordering': ['-administered_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vaccination_records/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='myapp.vaccinationappointment')),
            ],
        ),
    ]
