# Generated by Django 4.2.29 on 2026-03-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_vaccinationappointment_vaccinationrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='lost_found_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='myapp.lostpetreport'),
        ),
    ]
