# Generated by Django 4.2.29 on 2026-03-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customuser_profile_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_products/'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('packed', 'Packed'), ('delivered', 'Delivered')], default='packing', max_length=20),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='category',
            field=models.CharField(choices=[('pet_food', 'Pet Food'), ('toys', 'Toys'), ('grooming', 'Grooming'), ('accessories', 'Accessories'), ('medicines', 'Medicines'), ('others', 'Others')], max_length=20),
        ),
    ]
