# Generated by Django 4.2.29 on 2026-03-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_productinventory_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionlisting',
            name='adoption_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionlisting',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adoptionlisting',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_listings', to='myapp.animal'),
        ),
        migrations.AddField(
            model_name='adoptionlisting',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionlisting',
            name='vaccination_records',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='adoption_status',
            field=models.CharField(choices=[('available', 'In Care'), ('listed', 'Listed for Adoption'), ('adopted', 'Adopted')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], max_length=20),
        ),
    ]
