# Generated by Django 4.2.29 on 2026-03-14 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_adoptionlisting_adoption_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomerProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Groomer Product',
                'verbose_name_plural': 'Groomer Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.groomingsupply',),
        ),
        migrations.CreateModel(
            name='GroomingBooking',
            fields=[
            ],
            options={
                'verbose_name': 'Grooming Booking',
                'verbose_name_plural': 'Grooming Bookings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.servicebooking',),
        ),
        migrations.AlterField(
            model_name='groomingsupply',
            name='category',
            field=models.CharField(choices=[('shampoo', 'Shampoo'), ('brush', 'Brush'), ('conditioner', 'Conditioner'), ('clipper', 'Clipper'), ('blades', 'Grooming Blades'), ('ear_cleaning', 'Ear Cleaning Solution'), ('de_shedding', 'De-shedding Spray'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_usage_logs', to='myapp.servicebooking')),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usage_logs', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='myapp.groomingsupply')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
